<script lang="ts">
  import type {Icon} from 'src/_types'
  import {createEventDispatcher} from 'svelte'
  import TiEyeOutline from 'svelte-icons/ti/TiEyeOutline.svelte'
  import TiRefreshOutline from 'svelte-icons/ti/TiRefreshOutline.svelte'
  import TiCogOutline from 'svelte-icons/ti/TiCogOutline.svelte'
  import TiChevronRight from 'svelte-icons/ti/TiChevronRight.svelte'

  export let name: Icon
  export let direction: 'up' | 'down' | 'left' | 'right' = 'down'
  export let style: 'static' | 'button' = 'static'

  const onClickDispatcher = createEventDispatcher()

  const onClick = (ev: any) => {
    onClickDispatcher('click', ev)
  }
</script>

{#if name === 'chevron'}
  <div class={`icon-wrapper ${direction} ${style}`} on:click={onClick}>
    <TiChevronRight />
  </div>
{:else if name === 'settings'}
  <div class={`icon-wrapper settings ${style}`} on:click={onClick}>
    <TiCogOutline />
  </div>
{:else if name === 'eye-off'}
  <div class={`icon-wrapper ${style}`} on:click={onClick}>
    <TiEyeOutline />
  </div>
{:else if name === 'refresh-cw'}
  <div class={`icon-wrapper ${style}`} on:click={onClick}>
    <TiRefreshOutline />
  </div>
{/if}

<style>
  .icon-wrapper {
    width: var(--checklist-iconSize);
    height: var(--checklist-iconSize);
    transition: transform 150ms ease;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  /* Target the SVG generated by svelte-icons to ensure it fills the wrapper */
  :global(.icon-wrapper > svg) {
    width: 100%;
    height: 100%;
    display: block;
  }

  .up {
    transform: rotate(
      270deg
    ); /* TiChevronRight points right. Up needs -90 or 270 */
  }
  .down {
    transform: rotate(90deg); /* Right to Down is 90 */
  }
  .left {
    transform: rotate(180deg); /* Right to Left is 180 */
  }
  .right {
    transform: rotate(0deg); /* Right is default */
  }

  .button {
    color: var(--checklist-iconFill--accent);
    transition: color 150ms ease;
  }

  .button:hover {
    color: var(--checklist-textColor);
  }

  .static {
    color: var(--checklist-iconFill);
  }
</style>
